version: '3.8'

services:
  bot:
    build: .
    container_name: bot_container
    env_file: .env
    ports:
      - "8443:8443"
    depends_on:
      - db
    links:
      - db


  db:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_DB: vacancies_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db_data:
